In [1]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers, optimizers,datasets

In [3]:
a = tf.constant([1.2])
a,a.shape

(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.2], dtype=float32)>,
 TensorShape([1]))

In [5]:
a = tf.constant([1,2,3.])
a,a.shape

(<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>,
 TensorShape([3]))

In [7]:
a = tf.constant([[1,2],[3,4]])
a,a.shape

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]])>,
 TensorShape([2, 2]))

In [8]:
a = tf.constant([[[1,2],[3,4]],[[5,6],[7,8]]])
a,a.shape

(<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
 array([[[1, 2],
         [3, 4]],
 
        [[5, 6],
         [7, 8]]])>,
 TensorShape([2, 2, 2]))

In [12]:
a = tf.constant('Hello, Deep Learning')
tf.strings.lower(a)

<tf.Tensor: shape=(), dtype=string, numpy=b'hello, deep learning'>

In [14]:
#bool类型
a = tf.constant(True)
a

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [3]:
a = tf.constant([True,False])
a

<tf.Tensor: shape=(2,), dtype=bool, numpy=array([ True, False])>

In [4]:
tf.constant(123456789,dtype=tf.int16)

<tf.Tensor: shape=(), dtype=int16, numpy=-13035>

In [6]:
import numpy as np
np.pi
tf.constant(np.pi, dtype=tf.float64)

<tf.Tensor: shape=(), dtype=float64, numpy=3.141592653589793>

In [12]:
#精度转换
a = tf.constant(np.pi,dtype = tf.float16)
print('before：',a.dtype)
if a.dtype != tf.float32:
    a = tf.cast(a,tf.float32)
print('after:',a.dtype)

before： <dtype: 'float16'>
after: <dtype: 'float32'>


In [11]:
a

<tf.Tensor: shape=(), dtype=float16, numpy=3.14>

In [2]:
#通过 tf.Variable()函数可以将普通张量转换为待优化张量
tf.zeros([2,2])

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

In [3]:
tf.ones([3,2])

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [4]:
a = tf.ones([2,3])
tf.zeros_like(a)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [5]:
a = tf.zeros([3,2])
tf.ones_like(a)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [6]:
#通过tf.fill(shape,value)可以创建全为自定义数值的张量，例如，创建元素为-1的标量
tf.fill([],-1)

<tf.Tensor: shape=(), dtype=int32, numpy=-1>

In [7]:
#创建所有元素为-1的向量
tf.fill([1],-1)

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([-1])>

In [8]:
tf.fill([2,2],99)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[99, 99],
       [99, 99]])>

In [14]:
tf.random.normal([2,2])
tf.random.uniform([2,2],maxval=100,dtype=tf.int32)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[81, 90],
       [38,  5]])>

In [16]:
#tf.range(limit,delta=1)可以创建[0,limit)之间，步长为delta的整形序列，不包含limit本身。
tf.range(10)
tf.range(10,delta=2)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 2, 4, 6, 8])>

In [17]:
#通过tf.range(start,limit,delta=1)可以创建[start,limit),步长为delta的序列，不包含limit本身：
tf.range(1,10,delta=2)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 3, 5, 7, 9])>

In [2]:
out = tf.random.uniform([4,10])#随机模拟网络输出
y = tf.constant([2,3,2,0])#随机构造样本真实标签
y = tf.one_hot(y,depth=10)
loss = tf.keras.losses.mse(y,out)
loss = tf.reduce_mean(loss)
print(loss)

tf.Tensor(0.26742747, shape=(), dtype=float32)


In [4]:
#z=wx,模拟获得激活函数的输入z
z = tf.random.normal([4,2])
b = tf.zeros([2])#模拟偏置向量
z = z+b#累加偏置
z

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[ 0.60233784, -0.7106011 ],
       [ 0.47419584, -1.6493104 ],
       [ 0.48631668, -1.4533979 ],
       [-0.23133196,  0.04330752]], dtype=float32)>

In [8]:
#通过高层接口类Dense()方式创建网络层，张量W和b存储在类的内部，由类自动创建并管理。
#可以通过全连接层的bias成员变量查看偏置变量b，例如创建输入节点数为4，输出节点数为3的线性层网络，那么偏置向量长度应为3
fc = layers.Dense(3)
fc.build(input_shape=(2,4))
fc.bias#查看偏置


<tf.Variable 'bias:0' shape=(3,) dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>

In [6]:
x = tf.random.normal([2,4])
w = tf.ones([4,3])
b = tf.zeros([3])
o = x@w+b
o

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-0.18744332, -0.18744332, -0.18744332],
       [ 0.9928901 ,  0.9928901 ,  0.9928901 ]], dtype=float32)>

In [9]:
fc = layers.Dense(3)
fc.build(input_shape=(2,4))
fc.kernel

<tf.Variable 'kernel:0' shape=(4, 3) dtype=float32, numpy=
array([[-0.4543315 ,  0.29160762, -0.03079665],
       [-0.17069352, -0.04532039,  0.01355231],
       [-0.5533489 , -0.48549873, -0.2386679 ],
       [-0.062244  , -0.07328016,  0.65485156]], dtype=float32)>

In [7]:
(x_trian,y_train),(x_test,y_test)=keras.datasets.imdb.load_data(num_words=10000)

 5857280/17464789 [=========>....................] - ETA: 13:08

KeyboardInterrupt: 

In [ ]:
#将句子填充、截断为等长80个单词的句子
x_train = keras.preprocessing.sequence.pad_sequences(x_train,maxlen=80)
print(x_train.shape)
#创建数字编码的单词转换为词向量
out = embedding(x_train)
out.shape

In [9]:
#创建32*32的彩色图片输入，个数为4
x = tf.random.normal([4,32,32,3])
#创建卷积神经网络
layer = layers.Conv2D(16,kernel_size=3)
out = layer(x)
print(out.shape)
print(layer.kernel.shape)


(4, 30, 30, 16)
(3, 3, 3, 16)


In [10]:
import matplotlib.pyplot as plt
import pandas as pd
from sklearn import linear_model


ModuleNotFoundError: No module named 'matplotlib'

In [11]:
x = [2495, 2563, 2615, 2641, 2682, 2727, 2761, 2803, 2834, 2871]
x

[2495, 2563, 2615, 2641, 2682, 2727, 2761, 2803, 2834, 2871]

In [18]:
b = tf.constant([1,2])
b

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2])>

In [19]:
b = tf.expand_dims(b,axis=0)
b

<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[1, 2]])>

In [24]:
b = tf.tile(b,multiples=[2,1])
b

<tf.Tensor: shape=(32, 2), dtype=int32, numpy=
array([[1, 2],
       [1, 2],
       [1, 2],
       [1, 2],
       [1, 2],
       [1, 2],
       [1, 2],
       [1, 2],
       [1, 2],
       [1, 2],
       [1, 2],
       [1, 2],
       [1, 2],
       [1, 2],
       [1, 2],
       [1, 2],
       [1, 2],
       [1, 2],
       [1, 2],
       [1, 2],
       [1, 2],
       [1, 2],
       [1, 2],
       [1, 2],
       [1, 2],
       [1, 2],
       [1, 2],
       [1, 2],
       [1, 2],
       [1, 2],
       [1, 2],
       [1, 2]])>

In [28]:
x = tf.range(4)
x = tf.reshape(x,[2,2])
x = tf.tile(x,multiples=[1,2])
x = tf.tile(x,multiples=[2,1])
x

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[0, 1, 0, 1],
       [2, 3, 2, 3],
       [0, 1, 0, 1],
       [2, 3, 2, 3]])>

In [29]:
a = tf.random.normal([2,32,32,1])
b = tf.random.normal([32,32])

In [30]:
a+b

<tf.Tensor: shape=(2, 32, 32, 32), dtype=float32, numpy=
array([[[[ 1.64981890e+00,  2.03167772e+00,  1.28785443e+00, ...,
           7.11625397e-01,  3.08796167e+00,  8.46819222e-01],
         [ 8.20375681e-01, -1.43437672e+00, -1.65192401e+00, ...,
           2.00487614e+00,  3.32292467e-01, -9.90981817e-01],
         [ 2.37359142e+00, -1.87798738e-01,  3.38577688e-01, ...,
           5.84679425e-01,  1.28082442e+00, -6.35519803e-01],
         ...,
         [-4.42156434e-01, -7.08818197e-01, -4.43438649e-01, ...,
           6.11646652e-01, -9.95841384e-01, -1.44991919e-01],
         [-9.95074332e-01, -9.72164094e-01, -8.30665290e-01, ...,
           3.25655937e-01, -1.22224057e+00, -8.70719969e-01],
         [ 8.92628431e-02,  3.02425265e-01,  2.00664234e+00, ...,
           1.76199996e+00,  2.62124872e+00,  7.91904807e-01]],

        [[ 1.95846736e-01,  5.77705681e-01, -1.66117728e-01, ...,
          -7.42346704e-01,  1.63398957e+00, -6.07152879e-01],
         [ 2.51635480e+00,  2.6