#### 张量合并可以使用拼接（Concatenate）和堆叠（Stack）操作实现，拼接并不会产生新的维度，而堆叠会创建新维度。
#### 拼接 在 TensorFlow 中，可以通过 tf.concat(tensors, axis)，其中 tensors 保存了所有需要合并的张量 List， axis 指定需要合并的维度。
##### 合并操作可以在任意的维度上进行，唯一的约束是非合并维度的长度必须一致。

In [13]:
import tensorflow as tf
from tensorflow import keras

In [2]:
a = tf.random.normal([4,35,8])
b = tf.random.normal([6,35,8])
tf.concat([a,b],axis=0)#合并a，b

<tf.Tensor: shape=(10, 35, 8), dtype=float32, numpy=
array([[[ 1.93275779e-01,  5.08030653e-01, -1.31133962e+00, ...,
         -6.72901273e-01,  2.02918434e+00,  2.03824782e+00],
        [-8.60213041e-01,  4.57392454e-01,  1.32346869e-01, ...,
         -1.43011796e+00, -4.94464517e-01, -7.82813728e-01],
        [ 1.80016792e+00,  2.33464360e-01,  9.19613719e-01, ...,
         -2.06711125e+00,  1.04843843e+00,  1.29834628e+00],
        ...,
        [-2.18014582e-03,  1.15965426e+00,  1.39421237e+00, ...,
         -5.01604557e-01,  3.65309894e-01, -2.95172244e-01],
        [ 6.96983516e-01,  8.15567195e-01,  4.46087360e-01, ...,
         -2.60372114e+00, -1.84830397e-01, -2.61715472e-01],
        [ 3.69552106e-01,  9.80751693e-01, -7.73639381e-01, ...,
          6.19687513e-02, -1.33213031e+00, -1.57033920e+00]],

       [[ 8.15389276e-01,  3.89816165e-01,  7.82763600e-01, ...,
          3.82079452e-01,  1.05380642e+00,  1.31618416e+00],
        [-1.98734224e-01,  3.92225534e-01,  3.4199

#### 堆叠操作可以创建一个新的维度，例：张量A保存了某班成绩[35,8],张量B保存另一个班成绩，合并时希望创建一个新的维度来表示班级维度。

#### 使用tf.stack(tensors,axis)可以合并多个张量tensors，axis指定需要插入新维度的位置，用法与tf.expand_dims一致，当axis大于等于0时，在axis之前插入，当axis<0时，在axis之后插入。示意图见onenote

#### shape完全一致的shape才能进行堆叠


In [4]:
a = tf.random.normal([35,8])
b = tf.random.normal([35,8])
tf.stack([a,b],axis=-1)#堆叠合并为2个班级

<tf.Tensor: shape=(35, 8, 2), dtype=float32, numpy=
array([[[-0.63903075, -0.5111105 ],
        [-0.06051812, -0.31810632],
        [ 0.28528258,  0.54407877],
        [-0.7283729 ,  1.0176138 ],
        [ 0.08846822, -0.71118796],
        [ 0.96363926, -0.34102505],
        [ 0.8243536 ,  0.02116652],
        [-1.3509107 ,  0.07836318]],

       [[ 1.6217253 , -0.845178  ],
        [ 1.7266482 , -0.48110908],
        [ 0.24133019, -0.11285796],
        [-0.8628037 , -0.4130763 ],
        [-0.6104029 , -0.92633665],
        [-0.91563475, -0.88110363],
        [-1.0929263 ,  1.0150982 ],
        [-1.7173952 ,  0.06930593]],

       [[ 1.0978873 ,  1.3450955 ],
        [ 2.693263  , -0.97964495],
        [ 0.6192533 , -0.20836763],
        [ 0.7840318 , -1.3261887 ],
        [ 1.630611  ,  0.2119349 ],
        [ 0.7385528 ,  1.1325716 ],
        [-0.85099775, -1.1285347 ],
        [-0.34390303,  0.82657266]],

       [[-1.0519575 , -0.16133702],
        [-0.8931145 , -0.1316793 ],
      

#### 分隔操作，将一个张量拆分成多个张量
#### tf.split(x,axis,num_or_size_splits)可以完成张量的分割操作，其中，x：待分割张量；axis：分割的维度索引号；num_or_size_split：切割方案，当为单个数值时，表示分割成几份，为List时，表示每份的长度。

In [5]:
x = tf.random.normal([10,35,8])
result = tf.split(x,axis=0,num_or_size_splits=[4,2,2,2])
print(len(result))
result[0]

4


<tf.Tensor: shape=(4, 35, 8), dtype=float32, numpy=
array([[[-1.6303151 , -1.2812326 , -0.43092558, ...,  0.40719438,
          0.02371557,  1.4622698 ],
        [-0.9722778 ,  0.74207735,  0.06433932, ..., -1.5332367 ,
          0.9783127 ,  0.32708845],
        [-1.6976537 , -0.09065577,  0.45645985, ...,  0.21504611,
         -0.07594339,  0.07074731],
        ...,
        [ 0.06637941,  2.5816681 ,  0.5964875 , ...,  0.17714219,
         -0.45274714, -1.0785112 ],
        [-0.29468045, -0.24719651,  0.46189806, ...,  0.06714032,
         -0.116585  , -1.467851  ],
        [ 1.1313593 ,  0.7001314 , -0.5057109 , ..., -0.94411814,
          0.16428618,  1.411394  ]],

       [[-0.6055536 , -0.20510787,  0.61648136, ...,  0.19798169,
         -2.072325  ,  0.18409128],
        [ 0.7800466 ,  1.0565482 ,  1.2015196 , ..., -1.7455252 ,
          0.7691945 , -0.36583513],
        [ 1.3761399 ,  1.0317621 ,  0.14838992, ..., -1.4984415 ,
          0.8773444 , -0.95075953],
        ...,
  

In [6]:
#特别的，如果希望在某个维度上全部按长度为1的方式分割，还可以直接使用tf.unstack(x,axis)
x = tf.random.normal([10,35,8])
result = tf.unstack(x,axis=0)#unstack为长度为1
len(result)

10

#### L1 范数，定义为向量x的所有元素绝对值之和
#### L2 范数，定义为向量x的所有元素的平方和，再开根号
#### ∞ −范数，定义为向量x的所有元素绝对值的最大值
#### 在 TensorFlow 中，可以通过 tf.norm(x, ord)求解张量的 L1, L2, ∞等范数，其中参数 ord
#### 指定为 1,2 时计算 L1, L2 范数，指定为 np.inf 时计算∞ −范数
#### 通过 tf.reduce_max, tf.reduce_min, tf.reduce_mean, tf.reduce_sum 可以求解张量在某个维度上的最大、最小、 均值、和，也可以求全局最大、最小、均值、和信息。
#### 当不指定 axis 参数时， tf.reduce_*函数会求解出全局元素的最大、最小、 均值、和.
#### 通过 tf.argmax(x, axis)， tf.argmin(x, axis)可以求解在 axis 轴上， x 的最大值、 最小值所在的索引号

In [2]:
x = tf.random.normal([4,10])
tf.reduce_max(x,axis=1) # 统计概率维度上的最大值

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([1.4466057, 1.059273 , 1.0933518, 2.785893 ], dtype=float32)>

## 张量比较

In [9]:
#将预测结果与真实标签比较，统计比较结果中正确的数量来计算准确率。考虑100个样本的预测结果
out = tf.random.normal([100,10])
out = tf.nn.softmax(out,axis=1)#输出结果转换为概率
pred = tf.argmax(out,axis=1)#选取预测值
print("pred",pred)
#真实标签
y = tf.random.uniform([100],dtype=tf.int64,maxval=10)
#通过tf.equal(a,b)(或tf.math.equal(a,b))函数可以比较这2个张量是否相等
out = tf.equal(pred,y)
print("out:",out)
#布尔值转换成int型，统计True的个数
out = tf.cast(out,dtype=tf.float32)
correct = tf.reduce_sum(out)
print("correct:",correct)

pred tf.Tensor(
[3 7 3 3 6 8 7 7 7 6 8 6 0 1 1 9 7 9 4 3 4 7 4 1 4 9 8 0 5 5 1 1 3 5 3 8 2
 1 9 6 2 8 8 5 1 9 3 4 9 8 7 6 5 1 7 3 8 0 6 4 2 1 9 7 3 9 9 7 1 5 7 5 4 5
 4 0 0 3 5 9 5 3 1 6 8 1 4 0 4 8 4 6 8 2 1 1 2 3 2 7], shape=(100,), dtype=int64)
out: tf.Tensor(
[ True False False False  True False False False False False False False
 False False False False False False False False False False False False
 False False False False False  True False False False False False False
 False False  True False  True False False False False False False False
 False False False False  True False  True False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False  True  True False False False False False False
 False False False False], shape=(100,), dtype=bool)
correct: tf.Tensor(9.0, shape=(), dtype=float32)


#### 填充操作可以通过 tf.pad(x, paddings)函数实现， paddings 是包含了多个[Left padding, Right Padding]的嵌套方案 List，如[[0,0], [2,1], [1,2]]表示第一个维度不填充， 第二个维度左边(起始处)填充两个单元， 右边(结束处)填充一个单元， 第三个维度左边填充一个单元， 右边填充两个单元。 考虑上述 2 个句子的例子，需要在第二个句子的第一个维度的右边填充 2 个单元，则 paddings 方案为[[0,2]]

In [11]:
a = tf.constant([1,2,3,4,5,6])
b = tf.constant([7,8,1,6])
b = tf.pad(b,[[0,2]])#填充
print("b填充后:",b)
#填充后可以将a，b进行合并
c = tf.stack([a,b],axis=0)
print("a,b合并后:",c)

b填充后: tf.Tensor([7 8 1 6 0 0], shape=(6,), dtype=int32)
a,b合并后: tf.Tensor(
[[1 2 3 4 5 6]
 [7 8 1 6 0 0]], shape=(2, 6), dtype=int32)


#### 在自然语言处理中，需要加载不同句子长度的数据集，有些句子长度较小，如 10 个单词左右，部份句子长度较长，如超过 100 个单词。为了能够保存在同一张量中， 一般会选取能够覆盖大部分句子长度的阈值，如 80 个单词：对于小于 80 个单词的句子，在末尾填充相应数量的 0； 对大于 80 个单词的句子， 截断超过规定长度的部分单词。以 IMDB 数据集的加载为例

In [15]:
total_words = 10000#设定词汇量大小
max_review_len = 80#最大句子长度
embedding_len=100#词向量长度
#加载IMDB数据集
(x_train,y_train),(x_test,y_test) = keras.datasets.imdb.load_data(num_words=total_words)
#将句子填充或截断到相同长度，设置为末尾填充或末尾截断方式
x_train = keras.preprocessing.sequence.pad_sequences(x_train,maxlen=max_review_len,truncating='post',padding='post')
x_test = keras.preprocessing.sequence.pad_sequences(x_test,maxlen=max_review_len,truncating='post',padding='post')
print(x_train.shape,x_test.shape)

17465344/17464789 [==============================] - 35s 2us/step


NameError: name 'x_tarain' is not defined

In [16]:
x_train = keras.preprocessing.sequence.pad_sequences(x_train,maxlen=max_review_len,truncating='post',padding='post')
x_test = keras.preprocessing.sequence.pad_sequences(x_test,maxlen=max_review_len,truncating='post',padding='post')
print(x_train.shape,x_test.shape)

(25000, 80) (25000, 80)


In [17]:
#将28*28大小的图片数据填充成32*32大小的图片数据
x= tf.random.normal([4,28,28,1])
#将图片上下、左右各填充2个单元
tf.pad(x,[[0,0],[2,2],[2,2],[0,0]])

<tf.Tensor: shape=(4, 32, 32, 1), dtype=float32, numpy=
array([[[[ 0.        ],
         [ 0.        ],
         [ 0.        ],
         ...,
         [ 0.        ],
         [ 0.        ],
         [ 0.        ]],

        [[ 0.        ],
         [ 0.        ],
         [ 0.        ],
         ...,
         [ 0.        ],
         [ 0.        ],
         [ 0.        ]],

        [[ 0.        ],
         [ 0.        ],
         [ 0.5470995 ],
         ...,
         [-0.25156662],
         [ 0.        ],
         [ 0.        ]],

        ...,

        [[ 0.        ],
         [ 0.        ],
         [-0.3827423 ],
         ...,
         [ 0.2449681 ],
         [ 0.        ],
         [ 0.        ]],

        [[ 0.        ],
         [ 0.        ],
         [ 0.        ],
         ...,
         [ 0.        ],
         [ 0.        ],
         [ 0.        ]],

        [[ 0.        ],
         [ 0.        ],
         [ 0.        ],
         ...,
         [ 0.        ],
         [ 0.       

#### 通过tf.tile函数可以在任意维度将数据重复复制多份，如复制方案multiples=[2,3,3,1],表示通道数据不复制，高宽方向分别复制2份，图片数据再复制1份

In [18]:
#复制
x = tf.random.normal([4,32,32,3])
tf.tile(x,[2,3,3,1])#数据复制

<tf.Tensor: shape=(8, 96, 96, 3), dtype=float32, numpy=
array([[[[-1.49204040e+00, -1.05594955e-01, -1.51713574e+00],
         [-3.63523036e-01, -4.96893525e-01,  6.16865039e-01],
         [ 9.81882036e-01,  3.26198965e-01,  9.63776171e-01],
         ...,
         [ 5.72344482e-01, -1.62337959e+00,  1.21910363e-01],
         [-1.14716649e+00, -7.38591924e-02, -5.96671045e-01],
         [ 1.75308192e+00,  8.13480973e-01, -6.94836020e-01]],

        [[ 4.99744058e-01, -2.69512415e-01, -1.81171726e-02],
         [ 1.13223523e-01, -4.20862079e-01, -4.62426320e-02],
         [-5.61094917e-02, -1.01520741e+00, -4.77265686e-01],
         ...,
         [-7.68816054e-01, -6.02632761e-01,  4.76014376e-01],
         [ 8.15259933e-01,  3.25693429e-01,  9.46052790e-01],
         [ 7.32036769e-01, -6.33644402e-01,  1.05089605e+00]],

        [[-1.68974653e-01, -7.37279296e-01, -6.47244275e-01],
         [ 2.93438613e-01, -1.22370803e+00,  4.39843893e-01],
         [ 2.51049709e+00,  2.25762650e-01, 

#### 数据限幅，在TensorFlow中，可以通过tf.maxinmum(x,a)实现数据的下限幅，x[a,+inf];可以通过tf.minmum(x,a)实现数据的上限幅x[-inf,a]

In [24]:
x = tf.range(9)
print("x:",x)
#下限幅
x_L = tf.maximum(x,2)
print("下限幅：",x_L)
#上限幅
x_U = tf.minimum(x,7)
print("上限幅：",x_U)
#Relu函数实现
def relu(x):
    return tf.minumum(x,0.)
#通过组合 tf.maximum(x, a)和 tf.minimum(x, b)可以实现同时对数据的上下边界限幅：x ∈ [a, b]
y = tf.range(9)
y_LU = tf.minimum(tf.maximum(y,2),7)
print("y上下限幅后：",y_LU)
#更方便地，我们可以使用 tf.clip_by_value 实现上下限幅
z = tf.range(9)
z_LU = tf.clip_by_value(x,2,7)
print("z上下限幅后:",z_LU)

x: tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)
下限幅： tf.Tensor([2 2 2 3 4 5 6 7 8], shape=(9,), dtype=int32)
上限幅： tf.Tensor([0 1 2 3 4 5 6 7 7], shape=(9,), dtype=int32)
y上下限幅后： tf.Tensor([2 2 2 3 4 5 6 7 7], shape=(9,), dtype=int32)
z上下限幅后: tf.Tensor([2 2 2 3 4 5 6 7 7], shape=(9,), dtype=int32)
